export const COMPANY = {
  name: "대양전자",
  nameEn: "DAEYANG Electronics",
  phone: "010-3717-2207",
  email: "dye2000g@gmail.com",
  address: "인천광역시 동구 방축로 37번길 30 인천산업유통센터 8동 314호",
  ceo: "장종훈",
  established: "1994",
  businessNumber: "118-04-68314",
} as const;

export interface ProductCategory {
  id: string;
  name: string;
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  { id: "wireless", name: "무선통신 기기" },
  { id: "car-audio", name: "차량·음향기기" },
  { id: "fire-safety", name: "화재안전 시스템" },
  { id: "sensor", name: "센서·계측" },
  { id: "healthcare", name: "헬스케어·의료기기" },
  { id: "rfid", name: "RFID·자동인식" },
  { id: "industrial", name: "산업·생활기기" },
  { id: "development", name: "개발 서비스" },
];

export interface ProductSpec {
  label: string;
  value: string;
}

export interface ProductGroup {
  title: string;
  items: string[];
}

export interface Product {
  id: string;
  categoryId: string;
  name: string;
  image: string;
  description: string;
  overview: string;
  features: string[];
  specs?: ProductSpec[];
  groups?: ProductGroup[];
  note?: string;
  featured?: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: "lmr-radio",
    categoryId: "wireless",
    name: "VHF/UHF 듀얼밴드 LMR 무전기",
    image: "/images/products/lmr-radio.png",
    description: "VHF·UHF 동시 지원, 최대 50W 고출력의 전문 업무용 무전기",
    overview:
      "VHF/UHF 듀얼밴드 LMR 무전기는 산업 현장, 시설 관리, 공공 안전, 물류 창고, 건설 현장 및 각종 업무용 통신 환경에서 사용되는 전문 무선 통신 장비입니다. 하나의 장비로 VHF와 UHF 주파수 대역을 모두 지원하여 다양한 현장 환경에서 효율적인 현장 업무를 지원합니다.",
    features: [
      "VHF 및 UHF 주파수 동시 지원",
      "빈 채널 검색 및 최적 주파수 선택 가능",
      "채널 스캔 기능 지원",
      "중계기 및 다양한 무선망 구성 지원",
      "최대 50W 고출력 송신 지원",
      "장거리 통신 성능",
      "잡음 제거 기능 내장",
      "차량 및 고정국 설치 가능",
      "CTCSS / DCS 지원",
      "VOX 음성 자동 송신",
      "채널 잠금 기능",
      "비상 호출 기능",
      "그룹별 통신 운용 가능",
    ],
    specs: [
      { label: "주파수 범위", value: "VHF 136~174 MHz / UHF 400~470 MHz" },
      { label: "채널 수", value: "최대 200 채널" },
      { label: "채널 간격", value: "12.5 kHz / 25 kHz" },
      { label: "송신 출력", value: "5W / 25W / 50W 선택" },
      { label: "변조 방식", value: "FM (F3E)" },
      { label: "주파수 안정도", value: "±2.5 ppm" },
      { label: "수신 감도", value: "≤ 0.25 μV" },
      { label: "오디오 출력", value: "4W 이상" },
      { label: "스캔 기능", value: "지원" },
      { label: "CTCSS / DCS", value: "지원" },
      { label: "전원", value: "DC 13.8V ±15%" },
      { label: "동작 온도", value: "-20℃ ~ +60℃" },
      { label: "안테나 임피던스", value: "50 Ω" },
    ],
    featured: true,
  },
  {
    id: "cb-radio",
    categoryId: "wireless",
    name: "시티즌밴드(CB) 무전기",
    image: "/images/products/cb-radio.png",
    description: "면허 없이 사용 가능한 근거리 무선 통신 장비",
    overview:
      "CB 무전기는 별도의 면허 없이 사용 가능한 근거리 무선 통신 장비로, 주로 차량, 물류, 레저 활동에서 실용적인 커뮤니케이션을 제공합니다.",
    features: [
      "면허 없이 누구나 사용 가능",
      "차량용 및 휴대용으로 다양하게 활용",
      "채널 확장 가능 (Option)",
      "스캔 기능 (활성 채널 탐색)",
      "Squelch (잡음 제거)",
      "RF Gain 조절",
      "마이크 감도 조절",
      "PA 기능 (확성기 기능)",
    ],
    specs: [
      { label: "주파수 대역", value: "26.965 ~ 27.405 MHz" },
      { label: "채널 수", value: "40 채널 (400 채널 확장 가능)" },
      { label: "변조 방식", value: "AM / FM 지원" },
      { label: "출력 전력", value: "최대 약 4W (AM 기준)" },
      { label: "통신 거리", value: "약 1 ~ 10 km" },
      { label: "안테나", value: "외장 안테나 사용 (차량/고정형)" },
      { label: "전원", value: "DC 12V (차량용) 또는 어댑터" },
      { label: "스피커 출력", value: "내장 스피커 및 외부 스피커 연결 가능" },
    ],
  },
  {
    id: "frs-radio",
    categoryId: "wireless",
    name: "핸디 타입 FRS 생활무전기",
    image: "/images/products/frs-radio.png",
    description: "면허 없이 사용하는 초근거리 휴대용 생활무전기",
    overview:
      "FRS(Family Radio Service) 무전기는 면허 없이 누구나 사용할 수 있는 초근거리 휴대용 무전기로, 가정, 캠핑, 레저, 행사 등에서 활용하는 근거리 통신 솔루션입니다.",
    features: [
      "별도 허가 없이 사용 가능",
      "작고 가벼운 휴대성",
      "가족/팀 간 근거리 통신에 적합",
      "채널 선택 및 스캔 기능",
      "CTCSS / DCS (프라이버시 코드)",
      "VOX (음성 자동 송신)",
      "키패드 잠금 (Key Lock)",
      "배터리 절약 모드 (Power Save)",
    ],
    specs: [
      { label: "주파수 대역", value: "462 ~ 467 MHz (UHF)" },
      { label: "채널 수", value: "22 채널" },
      { label: "출력 전력", value: "1W" },
      { label: "통신 거리", value: "약 0.5 ~ 3 km (환경에 따라 변동)" },
      { label: "변조 방식", value: "FM" },
      { label: "전원", value: "AAA 배터리 4개" },
      { label: "디스플레이", value: "TFT LCD 화면 (채널/배터리 표시)" },
    ],
  },
  {
    id: "radar-detector",
    categoryId: "car-audio",
    name: "X 밴드 레이더 디텍터",
    image: "/images/products/radar-detector.png",
    description: "경찰 레이더 신호를 사전 감지하는 차량용 안전 보조 장치",
    overview:
      "X 밴드 레이더 디텍터는 도로에서 사용되는 경찰의 레이더 신호를 감지하여 운전자에게 사전 경고를 제공하는 차량용 장비로, 안전 운전을 돕는 보조 장치입니다.",
    features: [
      "교통경찰의 속도위반 레이더 신호 사전 감지 및 경고",
      "직관적인 시각·음성 알림 제공",
      "차량 내 간편 설치 및 사용",
      "장거리 감지 성능 (개방된 도로 환경에서 유리)",
      "거리에 따라 경고 (신호 강도 표시)",
      "도시/고속도로 모드 전환",
      "자동 음소거 (Auto Mute)",
      "전원 자동 ON/OFF",
    ],
    specs: [
      { label: "주파수 대역", value: "약 10.5 GHz (X Band)" },
      { label: "감지 거리", value: "약 수백 m ~ 수 km" },
      { label: "수신 방식", value: "슈퍼헤테로다인 수신 방식" },
      { label: "알림 방식", value: "LED / LCD 표시 + 경고음" },
      { label: "감도 조절", value: "고감도 / 저감도 모드" },
      { label: "필터 기능", value: "경보 감소 필터 (False Alert Filtering)" },
      { label: "전원 입력", value: "DC 12V (차량 시거잭)" },
      { label: "장착 방식", value: "대시보드 설치" },
      { label: "동작 온도", value: "-20℃ ~ +70℃" },
    ],
  },
  {
    id: "car-audio",
    categoryId: "car-audio",
    name: "고급 카오디오",
    image: "/images/products/car-audio.png",
    description: "DSP 음향 튜닝과 스마트폰 연동의 차량용 프리미엄 카오디오",
    overview:
      "강력한 출력과 프리미엄 음질을 제공하는 차량용 고급 카오디오 시스템입니다. 블루투스, USB, 스마트폰 연동 및 DSP 음향 튜닝 기능으로 최상의 드라이빙 사운드를 제공합니다.",
    features: [
      "고출력 디지털 오디오 앰프 내장 (CODEC 내장)",
      "고음질 DSP(Digital Signal Processor) 음향 튜닝 지원",
      "블루투스 오디오 및 핸즈프리 통화 기능",
      "USB / AUX / FM 라디오 지원",
      "스마트폰 미러링 및 MP3 재생 지원",
      "서브우퍼 및 멀티채널 스피커 확장 가능",
      "터치스크린 디스플레이 적용",
      "저왜곡·고해상도 오디오 출력",
      "차량 내부 환경에 최적화된 음장 효과 제공",
    ],
    specs: [
      { label: "출력 파워", value: "4 × 50W MAX" },
      { label: "오디오 채널", value: "4채널 스테레오" },
      { label: "지원 주파수", value: "FM 87.5 ~ 108 MHz (전세계 대응 가능)" },
      { label: "블루투스 버전", value: "Bluetooth 2.0" },
      { label: "지원 포맷", value: "MP3 / WMA / WAV" },
      { label: "입력 단자", value: "USB / AUX" },
      { label: "디스플레이", value: "7인치 TFT 터치 LCD" },
      { label: "전원 입력", value: "DC 12V 차량 전원" },
      { label: "음향 기능", value: "DSP / EQ / Bass Boost" },
      { label: "외부 출력", value: "RCA Pre-Out / Subwoofer Out" },
      { label: "지원 기능", value: "핸즈프리 / 스마트폰 연동 / 미러링" },
    ],
    featured: true,
  },
  {
    id: "audio-component",
    categoryId: "car-audio",
    name: "고급 오디오 콤포넌트 시스템",
    image: "/images/products/audio-component.png",
    description: "앰프·튜너·CD·스피커 독립 구성의 가정용 하이파이 오디오",
    overview:
      "오디오 콤포넌트 시스템은 가정용 고음질 음악 감상을 위한 전문 오디오 장비로, 앰프·튜너·CD 플레이어·스피커 등을 독립적으로 구성하여 풍부하고 정밀한 사운드를 제공합니다.",
    features: [
      "고출력 하이파이(Hi-Fi) 스테레오 시스템",
      "저왜곡·고해상도 오디오 재생",
      "앰프·튜너·CD 플레이어 독립형 구성",
      "블루투스 및 USB 음악 재생 지원",
      "풍부한 저음과 선명한 고음 구현",
      "다양한 외부 입력(AUX / RCA) 지원",
      "디지털 이퀄라이저 및 음장 효과 기능",
      "고급 우드 인클로저 스피커 적용",
      "리모컨 및 디지털 디스플레이 지원",
      "홈시어터 및 멀티미디어 연동 가능",
    ],
    specs: [
      { label: "출력 파워", value: "120W × 2 RMS" },
      { label: "오디오 채널", value: "2채널 스테레오" },
      { label: "지원 미디어", value: "CD / USB / Bluetooth" },
      { label: "지원 포맷", value: "MP3 / WAV / FLAC" },
      { label: "입력 단자", value: "AUX / RCA 스테레오" },
      { label: "블루투스 버전", value: "Bluetooth 3.0" },
      { label: "스피커 타입", value: "3Way Hi-Fi Speaker" },
      { label: "주파수 응답", value: "20Hz ~ 20kHz" },
      { label: "전원", value: "AC 220V / 110V 60Hz" },
      { label: "부가 기능", value: "EQ 조절 / 리모컨 / 디지털 디스플레이" },
    ],
  },
  {
    id: "wireless-fire-system",
    categoryId: "fire-safety",
    name: "무선 화재감지 시스템",
    image: "/images/products/wireless-fire-system.png",
    description: "감지기·중계기·수신기 무선 연동, 총 400개 감지기 관리 시스템",
    overview:
      "무선 화재감지 시스템은 화재 감지기와 중계기, 메인 수신기 간의 무선 통신을 통해 화재 신호를 실시간으로 전달하는 스마트 안전 관리 시스템입니다. 배선 공사를 최소화할 수 있어 설치가 간편하며, 공장·빌딩·창고·상업시설 등 다양한 환경에서 효율적인 화재 감시 및 경보 시스템 구축이 가능합니다.",
    features: [
      "무선 화재 감지 및 실시간 경보 기능",
      "감지기 ↔ 중계기 ↔ 메인 수신기 양방향 통신 지원",
      "배선 공사 최소화로 간편한 설치 가능",
      "장거리 무선 중계 및 다중 중계기 확장 지원",
      "화재 발생 위치 실시간 표시 기능",
      "중앙 메인 수신기 통합 모니터링 지원",
      "장애 및 통신 상태 자동 점검 기능",
      "화재·배터리·통신 이상 경보 지원",
      "실시간 이벤트 로그 및 상태 표시 기능",
      "공장, 빌딩, 창고, 학교, 병원 등 다양한 환경 적용 가능",
    ],
    specs: [
      { label: "감지 방식", value: "연기 감지(광전식) / 열 감지(정온식) / 복합식" },
      { label: "통신 방식", value: "FSK RF Wireless Communication" },
      { label: "사용 주파수", value: "447.2625MHz ~ 447.5625MHz" },
      { label: "통신 거리", value: "최대 100 ~ 1000m (환경 조건에 따라 상이)" },
      { label: "중계 기능", value: "자동 중계 및 다중 중계 지원" },
      { label: "표시 기능", value: "화재 / 통신 / 배터리 상태 표시" },
      { label: "경보 기능", value: "부저 및 메인 수신기 연동 경보" },
      { label: "전원 방식", value: "DC 12V / 내장 배터리 백업 (수신기)" },
      { label: "설치 방식", value: "천장형 / 벽부형" },
      { label: "운영 환경", value: "-10℃ ~ +50℃" },
      { label: "적용 장소", value: "빌딩 / 공장 / 물류창고 / 상업시설" },
    ],
    groups: [
      {
        title: "무선 감지기",
        items: [
          "연기 또는 열을 감지하여 화재 신호 전송",
          "1개의 감지기당 25채널 + 16개 ID 선택 가능",
        ],
      },
      {
        title: "무선 중계기",
        items: [
          "감지기 신호를 수신하여 메인 수신기로 전달",
          "1개의 중계기가 16개의 감지기 연결 가능",
        ],
      },
      {
        title: "메인 수신기",
        items: [
          "전체 감지기 상태 실시간 모니터링",
          "25개의 중계기 연결 및 총 400개 감지기 관리",
          "경보 출력 및 외부 시스템 연동 가능",
        ],
      },
    ],
    note: "무선 통신 기반의 스마트 화재감지 시스템으로 배선 공사 없이 간편하게 설치 가능하며, 실시간 화재 감지 및 중앙 모니터링 기능으로 안전한 시설 관리 환경을 제공합니다.",
    featured: true,
  },
  {
    id: "fire-alarm",
    categoryId: "fire-safety",
    name: "단독형 무선화재 경보기",
    image: "/images/products/fire-alarm.png",
    description: "배선 없이 설치하는 80dB 음성경보 단독형 화재경보기 (배터리 10년)",
    overview:
      "무선 통신 기반으로 배선 없이 간편하게 설치 가능한 단독형 무선 화재경보기로서, 실시간 연기 감지 시 강력한 음성경보 기능으로 가정과 다양한 시설의 화재 안전을 효과적으로 제공합니다.",
    features: [
      "화재 시 강력한 내장 음성경보 출력 (80dB 출력)",
      "무선 연동 기능 지원 (여러 개 경보기 상호 연동 연결 가능)",
      "배선 공사 없이 간편 설치 가능",
      "저전력 설계 및 배터리 상태 표시 기능 (10년 보증)",
      "매 24시간마다 인접 경보기와 자체 통신 점검 및 상태 유지",
      "테스트 및 리셋 버튼 내장",
      "가정, 사무실, 상가, 창고 등 다양한 장소 사용 가능",
    ],
    specs: [
      { label: "감지 방식", value: "연기 및 온도 감지 방식 (광전식, 정온식, 복합형)" },
      { label: "경보 음량", value: "80dB 이상" },
      { label: "통신 방식", value: "FSK RF Wireless" },
      { label: "사용 주파수", value: "447.2625MHz ~ 447.5625MHz" },
      { label: "통신 거리", value: "최대 100 ~ 1000m (환경 조건에 따라 상이)" },
      { label: "감지 면적", value: "최대 약 20~40㎡" },
      { label: "전원", value: "리튬이온 DC 3V / 6,000mAH 배터리" },
      { label: "배터리 수명", value: "약 10년" },
      { label: "표시 기능", value: "전원 / 경보 LED 표시" },
      { label: "설치 방식", value: "천장형" },
      { label: "사용 온도", value: "-10℃ ~ +50℃" },
    ],
  },
  {
    id: "bill-validator",
    categoryId: "industrial",
    name: "3권종 자판기용 지폐식별기",
    image: "/images/products/bill-validator.png",
    description: "위조 방지 기능을 갖춘 자판기용 3권종 지폐식별기",
    overview:
      "고속 지폐 인식과 안정적인 결제 기능을 제공하는 자판기용 3권종 지폐식별기입니다. 위조 방지 및 다양한 인터페이스 지원으로 무인 결제 시스템에 최적화된 솔루션을 제공합니다.",
    features: [
      "3권종 지폐 자동 인식 및 처리 기능",
      "고속 지폐 삽입 및 판별 지원",
      "위조지폐 감지 기능 내장",
      "다양한 자판기 및 무인기기 연동 가능",
      "RS-232 / Pulse 출력 인터페이스 지원",
      "지폐 걸림 및 오류 자동 감지 기능",
      "간편한 유지보수 및 탈부착 구조",
      "저전력 설계 및 안정적인 동작",
      "국내외 다양한 통화 설정 지원 가능",
    ],
    specs: [
      { label: "지원 권종", value: "3권종 (1,000원권, 5,000원권, 10,000원권)" },
      { label: "인식 방식", value: "광학 / 자기 센서 복합 인식" },
      { label: "인식 속도", value: "약 2~3초 이내" },
      { label: "삽입 방향", value: "4면 방향 삽입 지원" },
      { label: "인터페이스", value: "Pulse / RS-232" },
      { label: "사용 전압", value: "DC 12V" },
      { label: "소비 전류", value: "대기 150mA 이하" },
      { label: "적재 환경", value: "실내용" },
      { label: "사용 온도", value: "-10℃ ~ +50℃" },
      { label: "적용 기기", value: "자판기 / 무인판매기 / 티켓발매기" },
      { label: "재질", value: "난연성 ABS 및 금속 프레임" },
    ],
  },
  {
    id: "plc-water-level",
    categoryId: "sensor",
    name: "PLC 통신방식 수위감지 컨트롤러",
    image: "/images/products/plc-water-level.png",
    description: "전원선 통신(PLC) 2선식 구조의 산업용 수위 제어 컨트롤러",
    overview:
      "PLC(Power Line Communication) 통신방식 수위감지 컨트롤러는 전원선과 통신선을 함께 사용하는 2선식 구조로 수위 데이터를 안정적으로 전송하는 산업용 수위 제어 시스템입니다. 장거리 환경에서도 별도의 통신 배선 없이 센서와 컨트롤러 간의 데이터 통신이 가능하며, 실시간 수위 표시 및 경보 기능을 제공합니다.",
    features: [
      "PLC(Power Line Communication) 기반 2선식 통신 방식",
      "전원선과 데이터 통신 동시 사용 가능",
      "장거리 통신 지원 (최대 수백 m급)",
      "실시간 수위 측정 및 표시 기능",
      "센서 ↔ 컨트롤러 간 안정적인 데이터 전송",
      "아날로그 출력(DAC) 및 경보 출력 지원",
      "통신 이상 및 단선 감지 기능",
      "저전력 설계 및 산업 환경 대응",
      "FND/LED 상태 표시 기능 지원",
      "탱크, 저수조, 산업용 설비 등 다양한 환경 적용 가능",
    ],
    specs: [
      { label: "통신 방식", value: "PLC (Power Line Communication)" },
      { label: "배선 방식", value: "2선식" },
      { label: "측정 방식", value: "아날로그 수위 센서 / 레이저 수위 센서 입력" },
      { label: "표시 방식", value: "FND / LED 디지털 표시" },
      { label: "통신 거리", value: "최대 약 800m" },
      { label: "데이터 통신", value: "UART 기반 PLC 통신" },
      { label: "출력 기능", value: "DAC 아날로그 출력 / 경보 출력" },
      { label: "전원 입력", value: "DC 24V" },
      { label: "동작 온도", value: "-10℃ ~ +60℃" },
      { label: "적용 분야", value: "물탱크 / 산업설비 / 저수조 / 자동제어" },
    ],
    featured: true,
  },
  {
    id: "digital-thermometer",
    categoryId: "sensor",
    name: "J/K 센서 디지털 온도계",
    image: "/images/products/digital-thermometer.png",
    description: "J/K 열전대 지원, -50~1200℃ 산업용 디지털 온도계",
    overview:
      "J/K 타입 열전대(Thermocouple) 센서를 지원하는 디지털 온도계는 산업 현장의 다양한 온도를 정밀하게 측정하고 표시하는 고성능 온도 측정 장비입니다. 빠른 응답속도와 넓은 측정 범위를 제공하여 산업설비, 히터, 오븐, 제조 공정 및 연구 장비 등에 폭넓게 사용됩니다.",
    features: [
      "J-Type / K-Type 열전대 센서 지원",
      "고정밀 디지털 온도 표시 기능",
      "빠른 온도 응답 속도 제공",
      "넓은 온도 측정 범위 지원",
      "TFT LCD 디스플레이 적용",
      "온도 상·하한 경보 기능 지원",
      "산업용 노이즈 대응 설계 적용",
      "간편한 패널 장착 구조",
      "센서 단선 및 이상 감지 기능",
      "산업설비 및 자동제어 시스템 연동 가능",
    ],
    specs: [
      { label: "지원 센서", value: "J-Type / K-Type Thermocouple" },
      { label: "측정 범위", value: "-50℃ ~ +1200℃" },
      { label: "표시 방식", value: "LED / FND 디지털 표시" },
      { label: "표시 분해능", value: "0.1℃ / 1℃" },
      { label: "측정 정확도", value: "±0.5% FS" },
      { label: "입력 방식", value: "열전대 입력" },
      { label: "경보 기능", value: "상한 / 하한 Alarm 출력" },
      { label: "전원 입력", value: "AC 220V 또는 DC 9V 배터리" },
      { label: "출력 기능", value: "Relay / Analog Output (선택형)" },
      { label: "설치 방식", value: "핸디 타입 / 판넬 매립형" },
      { label: "사용 환경", value: "산업설비 / 히터 / 오븐 / 자동제어" },
    ],
  },
  {
    id: "bidet",
    categoryId: "industrial",
    name: "고급 비데 시스템",
    image: "/images/products/bidet.png",
    description: "온수 세정·온열 시트·자동 건조·탈취의 프리미엄 비데",
    overview:
      "프리미엄 기능과 위생 설계를 적용한 고급 비데 시스템입니다. 온수 세정, 온열 시트, 자동 건조 및 탈취 기능으로 더욱 쾌적하고 편안한 욕실 환경을 제공합니다.",
    features: [
      "온수 세정 및 마사지 세정 기능",
      "온열 시트 온도 조절 기능",
      "자동 탈취 및 위생 관리 기능",
      "노즐 자동 세척 및 항균 처리 적용",
      "사용자 맞춤 수압 및 온도 조절 가능",
      "리모컨 및 터치 조작 지원",
      "절전(ECO) 모드 지원",
      "부드러운 개폐 및 안전 설계 적용",
    ],
    specs: [
      { label: "세정 방식", value: "온수 세정 / 마사지 세정" },
      { label: "노즐 기능", value: "자동 세척 / 항균 노즐 / 위치 조정" },
      { label: "시트 기능", value: "온열 시트 온도 조절" },
      { label: "건조 기능", value: "온풍 건조" },
      { label: "탈취 기능", value: "자동 탈취 시스템" },
      { label: "조작 방식", value: "측면 버튼 / 무선 리모컨" },
      { label: "전원", value: "AC 220V / 60Hz" },
      { label: "소비 전력", value: "약 600~1200W" },
      { label: "안전 기능", value: "과열 방지 / 누전 차단" },
      { label: "설치 방식", value: "표준 양변기 장착형" },
      { label: "재질", value: "고강도 ABS / 항균 소재" },
    ],
  },
  {
    id: "blood-pressure",
    categoryId: "healthcare",
    name: "디지털 손목형 혈압계",
    image: "/images/products/blood-pressure.png",
    description: "원터치 자동 측정의 손목 착용형 디지털 혈압계 (의료기기)",
    overview:
      "간편한 손목 착용 방식의 디지털 혈압계로 혈압과 맥박을 쉽고 빠르게 측정할 수 있으며, 휴대성과 편의성을 갖춘 개인 건강 관리용 의료기기 제품입니다.",
    features: [
      "손목 착용형 자동 혈압 측정 방식",
      "수축기/이완기 혈압 및 맥박 동시 표시",
      "원터치 자동 측정 기능",
      "대형 LCD 디스플레이 적용",
      "측정 결과 메모리 저장 기능",
      "불규칙 맥박(IHB) 감지 기능",
      "휴대가 간편한 소형·경량 디자인",
      "자동 전원 차단 기능 지원",
      "저전력 설계 및 배터리 상태 표시",
      "가정 및 개인 건강 관리에 적합",
    ],
    specs: [
      { label: "측정 방식", value: "오실로메트릭 방식" },
      { label: "측정 범위", value: "혈압 0~299 mmHg" },
      { label: "맥박 측정 범위", value: "40~180 Pulse/min" },
      { label: "정확도", value: "혈압 ±3 mmHg / 맥박 ±5%" },
      { label: "디스플레이", value: "LCD 디지털 표시" },
      { label: "메모리 기능", value: "최대 60~90회 저장" },
      { label: "전원", value: "AAA 배터리 × 2" },
      { label: "자동 기능", value: "자동 측정 / 자동 전원 OFF" },
      { label: "착용 방식", value: "손목 밴드형" },
      { label: "사용 환경", value: "가정용 / 휴대용" },
      { label: "크기", value: "소형 경량 디자인" },
    ],
  },
  {
    id: "body-fat",
    categoryId: "healthcare",
    name: "핸디 타입 체지방계",
    image: "/images/products/body-fat.png",
    description: "양손 그립 BIA 방식의 휴대용 체성분 측정기 (의료기기)",
    overview:
      "핸디 타입 체지방계는 인체의 체지방률, 수분량, 근육량 등을 간편하게 측정할 수 있는 휴대용 건강 관리 기기로서, 양손 전극 센서를 이용한 생체 임피던스 분석(BIA) 방식을 적용하여 빠르고 간편한 측정이 가능한 개인 건강 관리용 의료기기 제품입니다.",
    features: [
      "체지방률 및 체성분 분석 기능",
      "생체 임피던스(BIA) 측정 방식 적용",
      "체지방·근육량·수분량 측정 지원",
      "간편한 양손 그립형 측정 방식",
      "대형 LCD 디지털 표시창 적용",
      "사용자 데이터 메모리 저장 기능",
      "남녀 및 연령별 측정 설정 지원",
      "소형·경량 휴대형 디자인",
      "자동 전원 차단 기능 지원",
      "개인 건강 및 체형 관리에 적합",
    ],
    specs: [
      { label: "측정 방식", value: "생체 임피던스 분석(BIA)" },
      { label: "측정 항목", value: "체지방률 / 근육량 / 수분량" },
      { label: "체지방 측정 범위", value: "5% ~ 50%" },
      { label: "사용자 설정", value: "성별 / 연령 / 신장 입력" },
      { label: "디스플레이", value: "LCD 디지털 표시" },
      { label: "메모리 기능", value: "사용자 데이터 저장 10개" },
      { label: "전원", value: "AAA 배터리 × 2" },
      { label: "자동 기능", value: "자동 측정 / 자동 전원 OFF" },
      { label: "사용 방식", value: "양손 그립형" },
      { label: "사용 환경", value: "가정용 / 헬스케어용" },
      { label: "재질", value: "ABS 플라스틱" },
    ],
  },
  {
    id: "hearing-aid",
    categoryId: "healthcare",
    name: "보청기와 피팅 스테이션",
    image: "/images/products/hearing-aid.png",
    description: "디지털 DSP 음향처리, 하울링 억제 보청기 및 피팅 솔루션",
    overview:
      "첨단 디지털 음향 처리 기술을 적용한 보청기로 선명한 음성과 편안한 청취 환경을 제공하여, 보다 자연스럽고 편리한 일상 소통을 지원합니다.",
    features: [
      "디지털 음향 신호 처리(DSP) 기술 적용",
      "주변 소음 감소 및 음성 강화 기능",
      "사용자 맞춤 음량 조절 지원",
      "충전식 또는 배터리 타입 선택 가능",
      "하울링(Feedback) 억제 기능 지원",
      "귀걸이형(BTE) / 귓속형(ITE) 모델 지원",
      "일상 생활 및 실외 환경에 적합",
    ],
    specs: [
      { label: "방식", value: "디지털 DSP 보청기" },
      { label: "주파수 범위", value: "약 200Hz ~ 6000Hz" },
      { label: "최대 출력", value: "110 ~ 130dB SPL" },
      { label: "음량 조절", value: "다단계 디지털 조절" },
      { label: "소음 제거", value: "Noise Reduction 지원" },
      { label: "하울링 제거", value: "Feedback Cancellation" },
      { label: "전원", value: "충전식 / 보청기 배터리" },
      { label: "사용 시간", value: "최대 약 20~40시간" },
      { label: "착용 방식", value: "귀걸이형(BTE) / 귓속형(ITE)" },
      { label: "적용 대상", value: "경도~중도 난청 사용자" },
    ],
    featured: true,
  },
  {
    id: "rfid-history",
    categoryId: "rfid",
    name: "RFID 제품이력조회 시스템",
    image: "/images/products/rfid-history.png",
    description: "생산·유통·검사 이력을 실시간 조회·관리하는 RFID 자동인식 시스템",
    overview:
      "RFID 기반 제품 이력조회 시스템으로 생산·유통·검사 정보를 실시간으로 조회 및 관리(Read/Write)하여, 물류 및 자산 관리의 효율성과 정확성을 향상시켜주는 스마트 자동인식 솔루션입니다.",
    features: [
      "RFID 태그 기반 제품 정보 자동 인식",
      "제품 생산·검사·유통 이력 조회 기능",
      "휴대형 RFID Read/Writer기 지원",
      "스마트폰 및 서버 연동 실시간 데이터 확인",
      "무선 통신 기반 데이터 전송 지원",
      "다중 RFID 태그 고속 인식 가능",
      "재고 및 물류 관리 자동화 지원",
      "제품 추적 및 자산 관리 기능 제공",
      "사용자 친화적 모바일 앱 인터페이스 지원",
      "산업·물류·유통 환경에 적합한 설계",
    ],
    specs: [
      { label: "인식 방식", value: "RFID Read / Write" },
      { label: "지원 주파수", value: "HF 13.56MHz / UHF 860~960MHz" },
      { label: "통신 방식", value: "Wi-Fi / Bluetooth / USB" },
      { label: "태그 인식 거리", value: "약 3cm ~ 1m (모델별 상이)" },
      { label: "표시 장치", value: "TFT LCD / 터치 디스플레이" },
      { label: "데이터 저장", value: "내부 메모리 및 서버 연동" },
      { label: "지원 기능", value: "제품 조회 / 기록 / 재고 관리" },
      { label: "인터페이스", value: "USB / RS-232 / 무선 LAN" },
      { label: "전원", value: "충전식 리튬 배터리" },
      { label: "운영 환경", value: "산업 및 물류 현장" },
      { label: "적용 분야", value: "생산관리 / 물류관리 / 자산관리" },
    ],
  },
  {
    id: "rfid-wireless",
    categoryId: "rfid",
    name: "RFID 무선 데이터 전송 시스템",
    image: "/images/products/rfid-wireless.png",
    description: "RFID 태그 정보를 중계기·수신기로 서버까지 실시간 전송하는 시스템",
    overview:
      "RFID 무선 전송 시스템은 RFID 태그에 저장된 제품 정보를 휴대형 RFID Read/Writer기로 읽어 무선 중계기 및 무선 수신기를 통해 PC 또는 관리 서버로 실시간 전송하는 스마트 자동인식 관리 시스템입니다. 제품 이력 관리, 물류 추적, 생산 관리 및 자산 관리 분야에서 효율적인 데이터 수집과 실시간 모니터링 환경을 제공합니다.",
    features: [
      "RFID 기반 비접촉 자동 인식 시스템",
      "제품 이력 실시간 무선 전송 기능",
      "휴대형 RFID 단말기 지원",
      "장거리 RF 무선 통신 가능",
      "무선 중계기 확장 지원",
      "PC 기반 통합 관리 시스템 제공",
      "물류·생산·자산 관리 자동화 지원",
      "실시간 데이터 조회 및 저장 가능",
      "설치 및 운영이 간편한 구조",
      "다양한 산업 환경 적용 가능",
    ],
    specs: [
      { label: "RFID 주파수", value: "HF 13.56MHz / UHF 860~960MHz" },
      { label: "통신 방식", value: "RF Wireless / Wi-Fi / Bluetooth" },
      { label: "통신 거리", value: "최대 100~500m" },
      { label: "RFID 인식 거리", value: "약 3cm ~ 1m" },
      { label: "데이터 전송 속도", value: "최대 115.2kbps" },
      { label: "리더기 인터페이스", value: "USB / RS-232 / Bluetooth" },
      { label: "수신기 인터페이스", value: "USB" },
      { label: "표시 장치", value: "TFT LCD" },
      { label: "전원", value: "충전식 리튬 배터리 / DC 5V" },
      { label: "사용 온도", value: "-10℃ ~ +50℃" },
      { label: "지원 기능", value: "조회 / 저장 / 분석 / 통계 (Software)" },
      { label: "적용 분야", value: "물류 / 생산 / 재고 / 자산 관리" },
    ],
    groups: [
      {
        title: "시스템 구성",
        items: [
          "RFID 태그 (RFID TAG)",
          "RFID Read/Writer기",
          "무선 중계기 (Wireless Repeater)",
          "무선 수신기 (Wireless Receiver)",
          "관리 소프트웨어",
        ],
      },
    ],
  },
  {
    id: "controller-board",
    categoryId: "development",
    name: "각종 컨트롤러 보드 HW & SW 개발",
    image: "/images/products/controller-board.png",
    description: "회로 설계부터 PCB·펌웨어까지 원스톱 임베디드 개발 서비스",
    overview:
      "다양한 산업 환경에 적용 가능한 컨트롤러 보드의 하드웨어 설계, 제작 및 임베디드 소프트웨어 개발 서비스를 제공합니다. MCU 기반 회로 설계, 통신 인터페이스, 센서 제어 및 사용자 맞춤형 Firmware 개발까지 Total Solution을 지원합니다.",
    features: [
      "Hardware와 Software를 연결하는 스마트 기술 개발",
      "IoT 기반 제품 Solution 제안 및 시제품 제작 가능",
      "경험을 바탕으로 한 신뢰성 높은 산업용 제어 솔루션 개발",
      "회로 설계부터 PCB 제작, Firmware까지 One-Stop 개발 가능",
      "고객 맞춤형 임베디드 시스템 개발 전문",
    ],
    groups: [
      {
        title: "개발 가능 지원분야",
        items: [
          "MCU Firmware Development",
          "Embedded System Design",
          "Industrial Controller Board Design",
          "Analog & Digital Circuit Design",
          "UART / RS-485 / RF / RFID Communication",
          "Sensor Interface & Control",
          "Power & PLC Communication Solution",
          "Custom Embedded Solution",
        ],
      },
    ],
    featured: true,
  },
];

export const NAV_ITEMS = [
  {
    label: "회사소개",
    href: "/company",
    children: [
      { label: "인사말", href: "/company" },
      { label: "연혁", href: "/company/history" },
      { label: "오시는 길", href: "/company/location" },
    ],
  },
  {
    label: "주요개발제품",
    href: "/products",
    children: PRODUCT_CATEGORIES.map((c) => ({
      label: c.name,
      href: `/products#${c.id}`,
    })),
  },
  {
    label: "기술지원",
    href: "/support",
    children: [
      { label: "자료실", href: "/support" },
      { label: "FAQ", href: "/support/faq" },
    ],
  },
  {
    label: "상담·견적 문의",
    href: "/contact",
  },
] as const;
